2020-10-21 22:21:43,340 INFO    MainThread:13152 [wandb_init.py:_log_setup():307] Logging user logs to wandb\run-20201021_222143-1plyi2fc\logs\debug.log
2020-10-21 22:21:43,340 INFO    MainThread:13152 [wandb_init.py:_log_setup():308] Logging internal logs to wandb\run-20201021_222143-1plyi2fc\logs\debug-internal.log
2020-10-21 22:21:43,340 INFO    MainThread:13152 [wandb_setup.py:_flush():68] setting env: {}
2020-10-21 22:21:43,340 INFO    MainThread:13152 [wandb_setup.py:_flush():68] setting user settings: {}
2020-10-21 22:21:43,340 INFO    MainThread:13152 [wandb_setup.py:_flush():68] multiprocessing start_methods=spawn
2020-10-21 22:21:43,340 WARNING MainThread:13152 [wandb_setup.py:_flush():68] Ignoring settings passed to wandb.setup() which has already been configured.
2020-10-21 22:21:43,341 INFO    MainThread:13152 [wandb_settings.py:_console():393] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable proper console logging on Windows. Falling back to wrapping stdout/err.
2020-10-21 22:21:43,918 WARNING MainThread:13152 [wandb_setup.py:__init__():208] Ignoring settings passed to wandb.setup() which has already been configured.
2020-10-21 22:21:46,191 INFO    MainThread:13152 [wandb_run.py:_console_start():1134] atexit reg
2020-10-21 22:21:46,192 INFO    MainThread:13152 [wandb_settings.py:_console():393] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable proper console logging on Windows. Falling back to wrapping stdout/err.
2020-10-21 22:21:46,192 INFO    MainThread:13152 [wandb_run.py:_redirect():1009] redirect: SettingsConsole.REDIRECT
2020-10-21 22:21:46,192 INFO    MainThread:13152 [wandb_run.py:_redirect():1012] Redirecting console.
2020-10-21 22:21:46,192 ERROR   MainThread:13152 [redirect.py:install():184] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable console logging on Windows.
2020-10-21 22:21:46,192 ERROR   MainThread:13152 [wandb_run.py:_redirect():1059] Failed to redirect.
Traceback (most recent call last):
  File "C:\Users\penci\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1052, in _redirect
    out_redir.install()
  File "C:\Users\penci\anaconda3\lib\site-packages\wandb\lib\redirect.py", line 185, in install
    raise Exception(msg)
Exception: Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable console logging on Windows.
2020-10-21 22:21:46,742 INFO    MainThread:13152 [wandb_run.py:_atexit_cleanup():1112] got exitcode: 0
2020-10-21 22:21:46,743 INFO    MainThread:13152 [wandb_run.py:_restore():1084] restore
2020-10-21 22:21:46,745 INFO    MainThread:13152 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "64b6135ba7694e1ea7b79479c4c3224e"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 552
    }
  }
}

2020-10-21 22:21:48,750 INFO    MainThread:13152 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "d020ad5cfc6b4fc2afc9d1370257054a"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 4
    }
    pusher_stats {
      uploaded_bytes: 6071
      total_bytes: 6071
    }
  }
}

2020-10-21 22:21:49,896 INFO    MainThread:13152 [wandb_run.py:_show_files():1363] logging synced files
2020-10-21 22:21:49,896 INFO    MainThread:13152 [internal.py:handle_exit():137] Internal process exited
