2020-10-21 22:20:20,489 INFO    MainThread:1180 [wandb_init.py:_log_setup():307] Logging user logs to wandb\run-20201021_222020-gw64fbdl\logs\debug.log
2020-10-21 22:20:20,490 INFO    MainThread:1180 [wandb_init.py:_log_setup():308] Logging internal logs to wandb\run-20201021_222020-gw64fbdl\logs\debug-internal.log
2020-10-21 22:20:20,490 INFO    MainThread:1180 [wandb_setup.py:_flush():68] setting env: {}
2020-10-21 22:20:20,490 INFO    MainThread:1180 [wandb_setup.py:_flush():68] setting user settings: {}
2020-10-21 22:20:20,490 INFO    MainThread:1180 [wandb_setup.py:_flush():68] multiprocessing start_methods=spawn
2020-10-21 22:20:20,490 WARNING MainThread:1180 [wandb_setup.py:_flush():68] Ignoring settings passed to wandb.setup() which has already been configured.
2020-10-21 22:20:20,492 INFO    MainThread:1180 [wandb_settings.py:_console():393] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable proper console logging on Windows. Falling back to wrapping stdout/err.
2020-10-21 22:20:21,100 WARNING MainThread:1180 [wandb_setup.py:__init__():208] Ignoring settings passed to wandb.setup() which has already been configured.
2020-10-21 22:20:23,623 INFO    MainThread:1180 [wandb_run.py:_console_start():1134] atexit reg
2020-10-21 22:20:23,623 INFO    MainThread:1180 [wandb_settings.py:_console():393] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable proper console logging on Windows. Falling back to wrapping stdout/err.
2020-10-21 22:20:23,623 INFO    MainThread:1180 [wandb_run.py:_redirect():1009] redirect: SettingsConsole.REDIRECT
2020-10-21 22:20:23,624 INFO    MainThread:1180 [wandb_run.py:_redirect():1012] Redirecting console.
2020-10-21 22:20:23,624 ERROR   MainThread:1180 [redirect.py:install():184] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable console logging on Windows.
2020-10-21 22:20:23,624 ERROR   MainThread:1180 [wandb_run.py:_redirect():1059] Failed to redirect.
Traceback (most recent call last):
  File "C:\Users\penci\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1052, in _redirect
    out_redir.install()
  File "C:\Users\penci\anaconda3\lib\site-packages\wandb\lib\redirect.py", line 185, in install
    raise Exception(msg)
Exception: Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable console logging on Windows.
2020-10-21 22:20:23,962 INFO    MainThread:1180 [wandb_run.py:_atexit_cleanup():1112] got exitcode: 0
2020-10-21 22:20:23,962 INFO    MainThread:1180 [wandb_run.py:_restore():1084] restore
2020-10-21 22:20:24,138 INFO    MainThread:1180 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "3aee2788fb8b4275958b15301920a68a"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 552
    }
  }
}

2020-10-21 22:20:26,155 INFO    MainThread:1180 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "a484e19a48694b95b6f50a8c883dcd2f"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 4
    }
    pusher_stats {
      uploaded_bytes: 6071
      total_bytes: 6071
    }
  }
}

2020-10-21 22:20:28,169 INFO    MainThread:1180 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "e88df9a8469d47d496b53633783a6478"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 4
    }
    pusher_stats {
      uploaded_bytes: 6071
      total_bytes: 6071
    }
  }
}

2020-10-21 22:20:29,313 INFO    MainThread:1180 [wandb_run.py:_show_files():1363] logging synced files
2020-10-21 22:20:29,313 INFO    MainThread:1180 [internal.py:handle_exit():137] Internal process exited
